### ISSUE TITLE
mod file specifies a go version that has not been released yet

### ISSUE THREAD

**Issue by krak3n** [go-lintpack/lintpack#48]
https://github.com/go-lintpack/lintpack/blob/master/go.mod#L3

This will break people using go modules in 1.11 since your package won't get compiled, I can't find much documentation on the `go` verb in the mod file, but I would suggest you remove it.

**Comment by Quasilyte** [comment]
This is a new behavior in vgo.
I'm not 100% sure what are the implications of that.
That line can probably be removed, but someone need to understand why it appeared there by default when using `go tip`.

For more context: https://go-review.googlesource.com/c/go/+/147279/2#message-83c45c7558eaa7e72da20dd8f3a0d7aceef099a1.

**Comment by krak3n** [comment]
Does your code rely on go1.12 features? If not then It's probably fine to remove the explicit go version from the mod file.

**Comment by krak3n** [comment]
My issue is you are downstream dependency of `github.com/golangci/golangci-lint` via `github.com/go-critic/checkers` and my pipelines broken because your package won't compile in 1.11 with modules on.

**Comment by Quasilyte** [comment]
> Does your code rely on go1.12 features? If not then It's probably fine to remove the explicit go version from the mod file.

It's not. But I use go tip and vgo adds that clause by default when doing `mod init`.
I wasn't adding that one by myself.

**Comment by krak3n** [comment]
You wanna look at this issue: https://github.com/golang/go/issues/28974

Also, why are you releasing against tip? `go mod init` in 1.11 will not add a `go` verb to the mod file. Go 1.11 is the current stable release and that's what you should be releasing.

**Comment by cristaloleg** [comment]
@Quasilyte as I've mentioned before it was caused by running `go mod` on tip, removing line with versions will fix this.
We don't have/planning any version dependent features in any implementation, so sticking to something particular makes zeo sense.

**Comment by Quasilyte** [comment]
Okay, then we can remove that line.
The reason why it was released by go tip is "it just happened".
I basically have only go tip on my main machine.
Anyone can send a PR that removes that line.
