### ISSUE TITLE
Close TempFile before deleting

### ISSUE THREAD

**Issue by Vysheslavtsev** [go-lintpack/lintpack#66]
OS Windows 10:
I get messages like

> cleanup failed: remove C:\Users\UserA\AppData\Local\Temp\linter844962311.go: The process cannot access the file because it is being used by another process.

This means that you delete the file before it is closed.

As you can see at:
https://github.com/go-lintpack/lintpack/blob/master/cmd/lintpack/build.go

```
	defer func() {
		if p.main != nil {
			if err := os.Remove(p.main.Name()); err != nil {
				log.Printf("cleanup failed: %v", err)
			}
		}
	}()
```

You have not any "close" for tmp file...

**Comment by quasilyte** [comment]
Thanks for reporting that and sorry for the long delay before the fix.
